"""
routers/reports.py
---------------------
REST API endpoints for PDF Reports.

    POST /api/v1/reports/{analysis_id}/generate
    GET  /api/v1/reports/{report_id}/download
    GET  /api/v1/reports

Matches src/services/reportService.js exactly.
"""

import uuid

from fastapi import APIRouter, Depends, HTTPException, Response, status
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.dependencies.auth import get_current_user
from app.models.user import User
from app.schemas.report import ReportResponse
from app.services import report_service
from app.services.exceptions import NotFoundError

router = APIRouter(prefix="/reports", tags=["PDF & Multi-Format Reports"])


@router.post(
    "/{analysis_id}/generate",
    response_model=ReportResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a PDF report for a completed analysis",
)
async def generate_report(
    analysis_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ReportResponse:
    try:
        report = await report_service.generate_report(db, analysis_id, current_user.id)
    except NotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

    # Re-fetch the enriched view so the response includes location_label etc.
    reports = await report_service.list_reports(db, current_user.id)
    match = next((r for r in reports if r["id"] == report.id), None)
    return ReportResponse(**match)


@router.get(
    "/{analysis_id}/export/pdf",
    status_code=status.HTTP_200_OK,
    summary="Stream dynamic PDF report directly",
)
async def export_pdf_report(
    analysis_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        pdf_bytes, land_name = await report_service.get_or_generate_pdf_bytes(db, analysis_id, current_user.id)
    except NotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

    safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in land_name).strip() or "land"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}-land-analysis-report.pdf"'},
    )


@router.get(
    "/{analysis_id}/export/excel",
    status_code=status.HTTP_200_OK,
    summary="Export multi-sheet Excel (.xlsx) workbook report",
)
async def export_excel_report(
    analysis_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        excel_bytes, land_name = await report_service.get_or_generate_excel_report(db, analysis_id, current_user.id)
    except NotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

    safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in land_name).strip() or "land"
    return Response(
        content=excel_bytes,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}-land-analysis-report.xlsx"'},
    )


@router.get(
    "/{analysis_id}/export/json",
    status_code=status.HTTP_200_OK,
    summary="Export comprehensive 15-section report payload in JSON",
)
async def export_json_report(
    analysis_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        json_data = await report_service.get_or_generate_json_report(db, analysis_id, current_user.id)
    except NotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

    return json_data


@router.get(
    "/{report_id}/download",
    status_code=status.HTTP_200_OK,
    summary="Download a generated PDF report",
)
async def download_report(
    report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    try:
        file_path, land_name = await report_service.get_report_file(db, report_id, current_user.id)
    except NotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc

    safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in land_name).strip() or "land"
    return FileResponse(
        path=file_path,
        media_type="application/pdf",
        filename=f"{safe_name}-analysis-report.pdf",
    )


@router.get(
    "",
    response_model=list[ReportResponse],
    status_code=status.HTTP_200_OK,
    summary="List all reports generated by the current user",
)
async def list_reports(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[ReportResponse]:
    data = await report_service.list_reports(db, current_user.id)
    return [ReportResponse(**item) for item in data]

