"""Make GIS fields nullable

Revision ID: ba1e1dbfed61
Revises: 3383c8c39d01
Create Date: 2026-08-26 15:21:23.046017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba1e1dbfed61'
down_revision: Union[str, None] = '3383c8c39d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lands', 'area_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('lands', 'road_width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('lands', 'soil_type',
               existing_type=postgresql.ENUM('CLAYEY', 'SANDY', 'LOAMY', 'ROCKY', 'BLACK_COTTON', 'RED_SOIL', name='soil_type_enum'),
               nullable=True)
    op.alter_column('lands', 'water_availability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lands', 'electricity_availability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    op.alter_column('lands', 'electricity_availability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('lands', 'water_availability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('lands', 'soil_type',
               existing_type=postgresql.ENUM('CLAYEY', 'SANDY', 'LOAMY', 'ROCKY', 'BLACK_COTTON', 'RED_SOIL', name='soil_type_enum'),
               nullable=False)
    op.alter_column('lands', 'road_width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('lands', 'area_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
